/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.BusinessTorneo;

/**
 *
 * @author PC
 */
public class EditarNodo extends javax.swing.JFrame {

    /**
     * Creates new form EditarNodo
     */
    
    private String idPeleador;
    private BusinessTorneo  _businessTorneo;
    
    public EditarNodo() {
        initComponents();
        _businessTorneo = new BusinessTorneo();
    }
    
    public void setFormulario(String idPeleador, String nombre, String poder, String edad){
        this.idPeleador = idPeleador;
        this.InputPersonaje1_Nombre.setText(nombre);
        this.InputPersonaje1_Poder.setText(poder);
        this.InputPersonaje1_Edad.setText(edad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCerrarVentana = new javax.swing.JButton();
        guardarEdicion = new javax.swing.JButton();
        labelNombrePersonaje = new javax.swing.JLabel();
        InputPersonaje1_Nombre = new javax.swing.JTextField();
        labelPoderPersonaje = new javax.swing.JLabel();
        InputPersonaje1_Poder = new javax.swing.JTextField();
        labelEdadPersonaje = new javax.swing.JLabel();
        InputPersonaje1_Edad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Editar Competidor");

        botonCerrarVentana.setBackground(new java.awt.Color(51, 102, 255));
        botonCerrarVentana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCerrarVentana.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarVentana.setText("X");
        botonCerrarVentana.setBorder(null);
        botonCerrarVentana.setBorderPainted(false);
        botonCerrarVentana.setContentAreaFilled(false);
        botonCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarVentana.setFocusPainted(false);
        botonCerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        guardarEdicion.setBackground(new java.awt.Color(51, 102, 255));
        guardarEdicion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarEdicion.setForeground(new java.awt.Color(255, 255, 255));
        guardarEdicion.setText("Guardar");
        guardarEdicion.setBorder(null);
        guardarEdicion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardarEdicion.setFocusPainted(false);
        guardarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarEdicionActionPerformed(evt);
            }
        });

        labelNombrePersonaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombrePersonaje.setForeground(new java.awt.Color(102, 102, 102));
        labelNombrePersonaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombrePersonaje.setText("Nombre:");

        InputPersonaje1_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputPersonaje1_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPersonaje1_NombreActionPerformed(evt);
            }
        });

        labelPoderPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPoderPersonaje.setForeground(new java.awt.Color(102, 102, 102));
        labelPoderPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPoderPersonaje.setText("Poder:");

        InputPersonaje1_Poder.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Poder.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputPersonaje1_Poder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPersonaje1_PoderActionPerformed(evt);
            }
        });

        labelEdadPersonaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelEdadPersonaje.setForeground(new java.awt.Color(102, 102, 102));
        labelEdadPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEdadPersonaje.setText("Edad:");

        InputPersonaje1_Edad.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Edad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputPersonaje1_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPersonaje1_EdadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputPersonaje1_Nombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombrePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPoderPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPersonaje1_Poder, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEdadPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InputPersonaje1_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(labelNombrePersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputPersonaje1_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelPoderPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(InputPersonaje1_Poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEdadPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(InputPersonaje1_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(guardarEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarEdicionActionPerformed
        String nombre = InputPersonaje1_Nombre.getText();
        String poder = InputPersonaje1_Poder.getText();
        String edad = InputPersonaje1_Edad.getText();
        var succes = _businessTorneo.modificarCompetidor(this.idPeleador, nombre, poder, edad);
        if (!succes) {
            System.out.println("ERROR al guardar cambios en el nodo");
        }
            this.dispose();
        
    }//GEN-LAST:event_guardarEdicionActionPerformed

    private void InputPersonaje1_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPersonaje1_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPersonaje1_NombreActionPerformed

    private void InputPersonaje1_PoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPersonaje1_PoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPersonaje1_PoderActionPerformed

    private void InputPersonaje1_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPersonaje1_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPersonaje1_EdadActionPerformed

    private void botonCerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarVentanaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCerrarVentanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarNodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarNodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputPersonaje1_Edad;
    private javax.swing.JTextField InputPersonaje1_Nombre;
    private javax.swing.JTextField InputPersonaje1_Poder;
    private javax.swing.JButton botonCerrarVentana;
    private javax.swing.JButton guardarEdicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelEdadPersonaje;
    private javax.swing.JLabel labelNombrePersonaje;
    private javax.swing.JLabel labelPoderPersonaje;
    // End of variables declaration//GEN-END:variables
}
