/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.BusinessTorneo;
import Model.Torneo.Competidor;
import java.util.LinkedList;

/**
 *
 * @author PC
 */
public class FormularioNuevoCombate extends javax.swing.JFrame {
    
    private BusinessTorneo _businessTorneo;
    
    public FormularioNuevoCombate() {
        _businessTorneo = new BusinessTorneo();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        Background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonCerrarVentana = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        labelNombrePersonaje1 = new javax.swing.JLabel();
        InputPersonaje1_Nombre = new javax.swing.JTextField();
        labelPoderPersonaje1 = new javax.swing.JLabel();
        InputPersonaje1_Poder = new javax.swing.JTextField();
        labelPersonaje1_Icono = new javax.swing.JLabel();
        InputPersonaje1_Icono = new javax.swing.JTextField();
        labelNombrePersonaje2 = new javax.swing.JLabel();
        InputPersonaje2_Nombre = new javax.swing.JTextField();
        labelPoderPersonaje2 = new javax.swing.JLabel();
        InputPersonaje2_Poder = new javax.swing.JTextField();
        labelPersonaje1_Icono1 = new javax.swing.JLabel();
        InputPersonaje2_Icono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        labelPersonaje1_Edad = new javax.swing.JLabel();
        InputPersonaje1_Edad = new javax.swing.JTextField();
        labelPersonaje2_Edad = new javax.swing.JLabel();
        InputPersonaje1_Icono2 = new javax.swing.JTextField();

        Background1.setBackground(new java.awt.Color(255, 255, 255));
        Background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jButton6.setBackground(new java.awt.Color(51, 102, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("X");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 460, Short.MAX_VALUE))
        );

        Background1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 500));

        jButton7.setBackground(new java.awt.Color(51, 102, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Detalles");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Background1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 100, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cuadro de Enfrentamientos");
        Background1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 860, 80));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        Background1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 720, 280));

        jButton8.setBackground(new java.awt.Color(51, 102, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Nuevo");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        Background1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 100, 30));

        jButton9.setBackground(new java.awt.Color(51, 102, 255));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Editar");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Background1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 100, 30));

        jButton10.setBackground(new java.awt.Color(51, 102, 255));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Eliminar");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        Background1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 100, 30));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Pre-Orden");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 100, 30));

        jButton11.setBackground(new java.awt.Color(51, 102, 255));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Pre-Orden");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        Background1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 410, 100, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        botonCerrarVentana.setBackground(new java.awt.Color(51, 102, 255));
        botonCerrarVentana.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonCerrarVentana.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarVentana.setText("X");
        botonCerrarVentana.setBorder(null);
        botonCerrarVentana.setBorderPainted(false);
        botonCerrarVentana.setContentAreaFilled(false);
        botonCerrarVentana.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarVentana.setFocusPainted(false);
        botonCerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 460, Short.MAX_VALUE))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VS");
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 330, 80));

        botonGuardar.setBackground(new java.awt.Color(51, 102, 255));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setText("Guardar");
        botonGuardar.setBorder(null);
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.setFocusPainted(false);
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        Background.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 80, 30));

        labelNombrePersonaje1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombrePersonaje1.setForeground(new java.awt.Color(102, 102, 102));
        labelNombrePersonaje1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombrePersonaje1.setText("Nombre:");
        Background.add(labelNombrePersonaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, 30));

        InputPersonaje1_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputPersonaje1_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPersonaje1_NombreActionPerformed(evt);
            }
        });
        Background.add(InputPersonaje1_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 210, -1));

        labelPoderPersonaje1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPoderPersonaje1.setForeground(new java.awt.Color(102, 102, 102));
        labelPoderPersonaje1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPoderPersonaje1.setText("Poder:");
        Background.add(labelPoderPersonaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 120, 30));

        InputPersonaje1_Poder.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Poder.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        InputPersonaje1_Poder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPersonaje1_PoderActionPerformed(evt);
            }
        });
        Background.add(InputPersonaje1_Poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 210, -1));

        labelPersonaje1_Icono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPersonaje1_Icono.setForeground(new java.awt.Color(102, 102, 102));
        labelPersonaje1_Icono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPersonaje1_Icono.setText("Icono:");
        Background.add(labelPersonaje1_Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 30));

        InputPersonaje1_Icono.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Icono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Background.add(InputPersonaje1_Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 210, -1));

        labelNombrePersonaje2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNombrePersonaje2.setForeground(new java.awt.Color(102, 102, 102));
        labelNombrePersonaje2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombrePersonaje2.setText("Nombre:");
        Background.add(labelNombrePersonaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 120, 30));

        InputPersonaje2_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje2_Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Background.add(InputPersonaje2_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 210, -1));

        labelPoderPersonaje2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPoderPersonaje2.setForeground(new java.awt.Color(102, 102, 102));
        labelPoderPersonaje2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPoderPersonaje2.setText("Poder:");
        Background.add(labelPoderPersonaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 120, 30));

        InputPersonaje2_Poder.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje2_Poder.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Background.add(InputPersonaje2_Poder, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 210, -1));

        labelPersonaje1_Icono1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPersonaje1_Icono1.setForeground(new java.awt.Color(102, 102, 102));
        labelPersonaje1_Icono1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPersonaje1_Icono1.setText("Icono:");
        Background.add(labelPersonaje1_Icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 120, 30));

        InputPersonaje2_Icono.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje2_Icono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Background.add(InputPersonaje2_Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 210, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo Combate");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 860, 80));

        botonCancelar.setBackground(new java.awt.Color(51, 102, 255));
        botonCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(null);
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.setFocusPainted(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        Background.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 120, 30));

        labelPersonaje1_Edad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPersonaje1_Edad.setForeground(new java.awt.Color(102, 102, 102));
        labelPersonaje1_Edad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPersonaje1_Edad.setText("Edad:");
        Background.add(labelPersonaje1_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 30));

        InputPersonaje1_Edad.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Edad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Background.add(InputPersonaje1_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, -1));

        labelPersonaje2_Edad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPersonaje2_Edad.setForeground(new java.awt.Color(102, 102, 102));
        labelPersonaje2_Edad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPersonaje2_Edad.setText("Edad:");
        Background.add(labelPersonaje2_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, 120, 30));

        InputPersonaje1_Icono2.setBackground(new java.awt.Color(255, 255, 255));
        InputPersonaje1_Icono2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Background.add(InputPersonaje1_Icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        //Peleador_1
        Competidor comp1 = new  Competidor();
        comp1.setNombre(InputPersonaje1_Nombre.getText());
        comp1.setIcono(InputPersonaje1_Icono.getText());
        comp1.setPoder(InputPersonaje1_Poder.getText());
        comp1.setEdad(InputPersonaje1_Edad.getText());
        boolean comp1Success = _businessTorneo.agregarCompetidor(comp1);
        
        //Peleador_2
        Competidor comp2 = new  Competidor();
        comp2.setNombre(InputPersonaje2_Nombre.getText());
        comp2.setIcono(InputPersonaje2_Icono.getText());
        comp2.setPoder(InputPersonaje2_Poder.getText());
        comp2.setEdad(InputPersonaje1_Icono2.getText());
        boolean comp2Success = _businessTorneo.agregarCompetidor(comp2);

        if(comp1Success && comp2Success){
            System.out.println("SE AGREGARON LOS PELEADORES EXITOSAMENTE");
        }else{
            System.out.println("UNO DE LOS PELEADORES NO SE AGREGO EXITOSAMENTE");
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonCerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarVentanaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCerrarVentanaActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        var coordenadas = this.getLocation();
        this.setVisible(false);
        
        Enfrentamientos viewEnfrentmientos = new Enfrentamientos();
        viewEnfrentmientos.setLocation(coordenadas);
        viewEnfrentmientos.setVisible(true);
        
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void InputPersonaje1_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPersonaje1_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPersonaje1_NombreActionPerformed

    private void InputPersonaje1_PoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPersonaje1_PoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPersonaje1_PoderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioNuevoCombate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioNuevoCombate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Background1;
    private javax.swing.JTextField InputPersonaje1_Edad;
    private javax.swing.JTextField InputPersonaje1_Icono;
    private javax.swing.JTextField InputPersonaje1_Icono2;
    private javax.swing.JTextField InputPersonaje1_Nombre;
    private javax.swing.JTextField InputPersonaje1_Poder;
    private javax.swing.JTextField InputPersonaje2_Icono;
    private javax.swing.JTextField InputPersonaje2_Nombre;
    private javax.swing.JTextField InputPersonaje2_Poder;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonCerrarVentana;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelNombrePersonaje1;
    private javax.swing.JLabel labelNombrePersonaje2;
    private javax.swing.JLabel labelPersonaje1_Edad;
    private javax.swing.JLabel labelPersonaje1_Icono;
    private javax.swing.JLabel labelPersonaje1_Icono1;
    private javax.swing.JLabel labelPersonaje2_Edad;
    private javax.swing.JLabel labelPoderPersonaje1;
    private javax.swing.JLabel labelPoderPersonaje2;
    // End of variables declaration//GEN-END:variables
}
